### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by aclemon** [Janche/sso-oauth2-server#1]
OAuth Error
error="invalid_grant", error_description="Invalid redirect: http://192.168.1.111:8087/login does not match one of the registered values."

![image](https://user-images.githubusercontent.com/28623175/108630107-289d8a00-749e-11eb-9c4b-1132404d5098.png)

**Comment by aclemon** [comment]
![image](https://user-images.githubusercontent.com/28623175/108630122-40750e00-749e-11eb-9913-f5dc8832e812.png)

**Comment by Janche** [comment]
> OAuth错误
> error =“ invalid_grant”，error_description =“无效的重定向：[http](http://192.168.1.111:8087/login) : [//192.168.1.111](http://192.168.1.111:8087/login) :8087/login与注册值之一不匹配。
> 
> ![图像](https://user-images.githubusercontent.com/28623175/108630107-289d8a00-749e-11eb-9c4b-1132404d5098.png)



> OAuth Error
> error="invalid_grant", error_description="Invalid redirect: http://192.168.1.111:8087/login does not match one of the registered values."
> 
> ![image](https://user-images.githubusercontent.com/28623175/108630107-289d8a00-749e-11eb-9c4b-1132404d5098.png)

你数据库的重定向地址是 用的我默认的还是，你自己改的，看下你改后和这个匹配不 http://192.168.1.111:8087/login
